<a href="https://colab.research.google.com/github/prveena/datascience/blob/master/course_outcome_1_qs_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Array type ",type(arr))
print("Array dimension ",arr.ndim)
print("Array shape ",arr.shape)
print("Array size ",arr.size)

In [ ]:
list=[1,2,3,4,5,6]
print("List to array ")
print(np.asarray(list))

List to array 
[1 2 3 4 5 6]


In [ ]:
tuple=([1,2,3],[4,5,6])
print("Tuple to array ")
print(np.asarray(tuple))

Tuple to array 
[[1 2 3]
 [4 5 6]]


In [ ]:
l=[1,2,3]
arr=np.array(l)
print("One dimensional array ",arr)
print("Dimension ",arr.ndim)

One dimensional array  [1 2 3]
Dimension  1


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Two dimensional array ",arr)
print("Dimension ",arr.ndim)

Two dimensional array  [[1 2 3]
 [4 5 6]]
Dimension  2


In [ ]:
arr=np.array([[1,2,3],[9,4,5]])
print("Shape ",arr.shape)
print(arr)
arr.shape=3,2
print(arr)


Shape  (2, 3)
[[1 2 3]
 [9 4 5]]
[[1 2]
 [3 9]
 [4 5]]


In [ ]:
a=np.zeros((3,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
a=np.ones((3,2),dtype=int)
print(a)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
a=np.eye(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
print("A = ",np.arange(3,20,2))

A =  [ 3  5  7  9 11 13 15 17 19]


In [ ]:
arr1=([[1,2,3],[4,5,6]])
arr2=([[4,5,6],[9,7,8]])

print("Sum of two matrix ",np.add(arr1,arr2))

Sum of two matrix  [[ 5  7  9]
 [13 12 14]]


In [ ]:
a=([[6,7,8],[2,3,1]])
b=([[8,7,6],[6,3,2]])
print("A-B =",np.subtract(a,b))
print("B-A =",np.subtract(b,a))
print("A**2 =",np.power(a,2))
print("A*B =",np.multiply(a,b))
print("A/B =",np.divide(a,b))

A-B = [[-2  0  2]
 [-4  0 -1]]
B-A = [[ 2  0 -2]
 [ 4  0  1]]
A**2 = [[36 49 64]
 [ 4  9  1]]
A*B = [[48 49 48]
 [12  9  2]]
A/B = [[0.75       1.         1.33333333]
 [0.33333333 1.         0.5       ]]


In [ ]:
print("A =",np.linspace(1,10,num=5,endpoint=True,retstep=True))
print("B =",np.linspace(1,10,num=5,endpoint=True,retstep=True,dtype=int))
print("c =",np.linspace(1,10,num=5,endpoint=True))

A = (array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)
B = (array([ 1,  3,  5,  7, 10]), 2.25)
c = [ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
a=np.array([3,4,5,6,1,6])
print("Original array= ",a)
b=a.reshape(2,3)
print("Reshaped array =",b)

Original array=  [3 4 5 6 1 6]
Reshaped array = [[3 4 5]
 [6 1 6]]


In [ ]:
a=np.array([[1,2,3],[5,6,7]])
b=np.resize(a,(3,2))
print("Resized array =",b)


Resized array = [[1 2]
 [3 5]
 [6 7]]
