<a href="https://colab.research.google.com/github/prveena/datascience/blob/master/ds_co1_qs4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
x=[1,2,3]
ser=pd.Series(x)
print(ser)


0    1
1    2
2    3
dtype: int64


In [ ]:
x=np.array(['Apple','Banana','Grapes'])
ser=pd.Series(x,index=['A','B','G'])
print(ser['A'])

Apple


In [ ]:
x=['Apple','Banana','Grapes']
ser=pd.Series(x)
print(ser)

0     Apple
1    Banana
2    Grapes
dtype: object


In [ ]:
x=pd.Index([1,2,0,3,4])
y=pd.Index([2,7,8,6,9])
print(x,'\n' ,y)


Int64Index([1, 2, 0, 3, 4], dtype='int64') 
 Int64Index([2, 7, 8, 6, 9], dtype='int64')


In [ ]:
x.append(y)

Int64Index([1, 2, 0, 3, 4, 2, 7, 8, 6, 9], dtype='int64')

In [ ]:
x=[i for i in range(50)  if (i%2==0) and (i%3==0)]
ser=pd.Series(x)
print(ser[1:])

1     6
2    12
3    18
4    24
5    30
6    36
7    42
8    48
dtype: int64


In [ ]:
l=['read','write','speak','hear']
x=pd.DataFrame(l)
print(x)

       0
0   read
1  write
2  speak
3   hear


In [ ]:
dict={'Name':['Roy','Raj','Sam'],'Age':[11,12,13]}
y=pd.DataFrame(dict)
print(y)

  Name  Age
0  Roy   11
1  Raj   12
2  Sam   13


In [ ]:
s=pd.Series([67,56,67,34])
index_=['CSE','EEE','ECE','ME']
s.index=index_
print(s)

CSE    67
EEE    56
ECE    67
ME     34
dtype: int64


In [ ]:
x=[12,23,14,14]
s=pd.Series(x,index=['MCA','BCA','MBA','BBA'])
print(s)

MCA    12
BCA    23
MBA    14
BBA    14
dtype: int64


In [ ]:
data={'Percentage':['78%','89%','76%','50%','90%'],
      'Grade':['B','A','B','D','A']}
s=pd.DataFrame(data,index=['Anu','Anju','Roy','Manu','Sam'])
print(s)

     Percentage Grade
Anu         78%     B
Anju        89%     A
Roy         76%     B
Manu        50%     D
Sam         90%     A


In [ ]:
print(s.loc[['Anju']])

     Percentage Grade
Anju        89%     A


In [ ]:
import csv
with open('data.csv','rt') as f:
  data=csv.reader(f)
  for row in data:
    print(row)

['\ufeffProgramming language', 'Designed by', 'Appeared', 'Extension']
['Python', 'Guido van Rossum', '1991', '.py']
['Java', 'James Gosling', '1995', '.java']
['C++', 'Bjarne Stroustrup', '1983', '.cpp']


In [ ]:
m=pd.read_csv('/content/mark.csv')
print(m)

    Name Class  Total marks
0    ANU   CSE          190
1   ANJU   CSE          156
2   ARYA   EEE          178
3  MANJU   EEE          145
4  GRACE   ECE          130


In [ ]:
m=pd.read_csv('/content/MARK1.csv')
print(m)

    Name Class  Total marks
0    ANU   CSE        190.0
1   ANJU   CSE        156.0
2   ARYA   EEE        178.0
3  MANJU   EEE        145.0
4  GRACE   ECE        130.0
5    NaN   NaN          NaN
6    ANU   CSE        190.0
7   ANJU   CSE        156.0


In [ ]:
m=pd.read_csv('/content/data.csv')
print(m)

  Programming language        Designed by  Appeared Extension
0               Python   Guido van Rossum      1991       .py
1                 Java      James Gosling      1995     .java
2                  C++  Bjarne Stroustrup      1983      .cpp


In [ ]:
m=pd.read_csv('/content/data.csv')
m.corr()

Appeared
Appeared       1.0

In [ ]:
m=pd.read_csv('/content/MARK1.csv')
d=m.head()
print(d)

    Name Class  Total marks
0    ANU   CSE        190.0
1   ANJU   CSE        156.0
2   ARYA   EEE        178.0
3  MANJU   EEE        145.0
4  GRACE   ECE        130.0


In [ ]:
m=pd.read_csv('/content/MARK1.csv')
d=m.tail()
print(d)

    Name Class  Total marks
3  MANJU   EEE        145.0
4  GRACE   ECE        130.0
5    NaN   NaN          NaN
6    ANU   CSE        190.0
7   ANJU   CSE        156.0


In [ ]:
m=pd.read_csv('/content/MARK1.csv')
m.dropna()


Name Class  Total marks
0    ANU   CSE        190.0
1   ANJU   CSE        156.0
2   ARYA   EEE        178.0
3  MANJU   EEE        145.0
4  GRACE   ECE        130.0
6    ANU   CSE        190.0
7   ANJU   CSE        156.0

In [ ]:
m=pd.read_csv('MARK1.csv')
a=m.drop_duplicates(["Total marks"])
print(a)


    Name Class  Total marks
0    ANU   CSE        190.0
1   ANJU   CSE        156.0
2   ARYA   EEE        178.0
3  MANJU   EEE        145.0
4  GRACE   ECE        130.0
5    NaN   NaN          NaN


In [ ]:
m.corr()

Total marks
Total marks          1.0

In [ ]:
m=pd.read_csv('MARK1.csv')
m.corr()

Total marks
Total marks          1.0

In [ ]:
a=np.matrix('[4,2,3;4,5,6;7,8,5]') 
print("A=",a)
t=a.transpose()
print("Transpose of a m A=",t)                             

A= [[4 2 3]
 [4 5 6]
 [7 8 5]]
Transpose of a m A= [[4 4 7]
 [2 5 8]
 [3 6 5]]


In [ ]:

import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[4,3,2,5]])
print(a)
from numpy.linalg import svd
np.linalg.svd(a)



[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 5]]


(array([[-0.33444699, -0.4468054 ,  0.82976511],
        [-0.82972967, -0.27789304, -0.48407037],
        [-0.44687121,  0.85037662,  0.27778721]]),
 array([15.86708582,  2.24061238,  1.10238096]),
 array([[-3.95194194e-01, -4.40401327e-01, -4.85608460e-01,
         -6.43469224e-01],
        [ 6.98575028e-01, -4.39130018e-03, -7.07357629e-01,
          1.07790684e-01],
        [-4.34911269e-01, -3.73310488e-01, -3.11709707e-01,
          7.57844658e-01],
        [-4.08248290e-01,  8.16496581e-01, -4.08248290e-01,
          2.22339288e-16]]))

In [ ]:
u,s,vp=svd(a,full_matrices=True)
print(u)


[[-0.33444699 -0.4468054   0.82976511]
 [-0.82972967 -0.27789304 -0.48407037]
 [-0.44687121  0.85037662  0.27778721]]


In [ ]:
print(s)

[15.86708582  2.24061238  1.10238096]


In [ ]:
print(vp)

[[-3.95194194e-01 -4.40401327e-01 -4.85608460e-01 -6.43469224e-01]
 [ 6.98575028e-01 -4.39130018e-03 -7.07357629e-01  1.07790684e-01]
 [-4.34911269e-01 -3.73310488e-01 -3.11709707e-01  7.57844658e-01]
 [-4.08248290e-01  8.16496581e-01 -4.08248290e-01  2.22339288e-16]]
