<a href="https://colab.research.google.com/github/prveena/datascience/blob/master/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import svd
a = np.array([[1,2,3],[4,5,6]]) 
np.linalg.svd(a)

(array([[-0.3863177 , -0.92236578],
        [-0.92236578,  0.3863177 ]]),
 array([9.508032  , 0.77286964]),
 array([[-0.42866713, -0.56630692, -0.7039467 ],
        [ 0.80596391,  0.11238241, -0.58119908],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [ ]:
u,s,vt=svd(a,full_matrices=True)
print(u.shape,s.shape,vt.shape)

(2, 2) (2,) (3, 3)


In [ ]:
print(u)
print(s)
print(vt)